SESI 4 - NUMPY

In [1]:
import numpy as np

a = np.array([1,2,3,])
a

array([1, 2, 3])

In [3]:
#create array filled with 0s

np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [4]:
#creat array filled with 1s

np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [5]:
#create empty array 
#the function empty creates an array whose initial content is random and depends on the state of the memory

np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [6]:
#create array with a range of elements

print(np.arange(4))
print(np.arange(0,10,2)) #(start, stop, step)

[0 1 2 3]
[0 2 4 6 8]


Add, Remover, Sort

In [7]:
arr = np.array([1,2,3,4,5,6,7,8])
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [9]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [10]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

Shape and Size

In [11]:
array_example = np.array([[[0,1,2,3], 
                           [4,5,6,7]],

                           [[0,1,2,3], 
                            [4,5,6,7]],

                           [[0,1,2,3], 
                            [4,5,6,7]]])

print(array_example)                           

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [12]:
array_example.ndim

3

In [13]:
array_example.size

24

In [14]:
array_example.shape

(3, 2, 4)

Reshape

In [15]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [16]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [17]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

Convert 1D to 2D

In [18]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [19]:
#add axis
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [20]:
#convert 1D array to a row vector by inserting an axis along the first dimension
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector) 

(1, 6)
[[1 2 3 4 5 6]]


In [21]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [22]:
#use np.expand_dims to add an axis at index position 1 with:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [23]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

Indexing and Slicing

In [26]:
data = np.array([1,2,3])
print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [28]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [35]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


Creating Array from Existing Data

In [36]:
#np.vstack (numpuk vertikal)
a_1 = np.array([[1,1], 
                [2,2]])

a_2 = np.array([[3,3],
                [4,4]])

np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [37]:
#np.hstack (numpuk horizontal)
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [39]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12], 
                     [13,14,15,16,17,18,19,20,21,22,23,24]])
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [42]:
#if you wanted to split this array into three equally shaped arrays
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [43]:
#you can create a new array object that looks at the same data
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Basic Array Operations

In [45]:
a = np.array([1,2,3,4])
a.sum()

10

In [50]:
b = np.array([[1,1], [2,2]])
b.sum(axis=0) #sum the rows

array([3, 3])

In [51]:
b.sum(axis=1) #sum the columns

array([2, 4])

In [56]:
data = np.array([1,2])
ones = np.ones(2)

array([1., 1.])

In [57]:
data

array([1, 2])

In [58]:
ones

array([1., 1.])

In [59]:
data + ones


array([2., 3.])

In [60]:
data * data

array([1, 4])

In [61]:
data / data

array([1., 1.])

Broadcasting

In [62]:
data * 2

array([2, 4])